In [1]:
import os
import sys
import numpy as np
import sklearn as skl
import time
import torch
import matplotlib.pyplot as plt
import torch.nn as nn
from sklearn.model_selection import train_test_split

sys.path.append("../../../")
import CalibratedTimeseriesModels

from CalibratedTimeseriesModels.utils import *
from CalibratedTimeseriesModels.models.gnn import *
from CalibratedTimeseriesModels.evaluators import ExplicitEvaluator

%load_ext autoreload
%autoreload 2

In [2]:
# load data
X_orig = torch.load("../../../datasets/processed/openEI/X_openei_011_subset_multitask.pt")
Y_orig = torch.load("../../../datasets/processed/openEI/Y_openei_011_subset_multitask.pt")

X = X_orig[0,:,:24].unsqueeze(-1).float()
Y = Y_orig[0,:,:6].unsqueeze(-1).float()

In [3]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1, random_state=1)
X_train, X_val, Y_train, Y_val = train_test_split(X_train, Y_train, train_size = 0.7/0.9,random_state=1)
X_batches, Y_batches = batch(X_train, Y_train)

In [4]:
hidden_layers = [20, 20, 20]
model = GaussianNeuralNet(1, 24, hidden_layers, 1, 6)

In [5]:
train(model, X_batches, Y_batches, num_epochs=40)

epoch : 1, loss: -1.1574
epoch : 2, loss: -5.3022
epoch : 3, loss: -6.3277
epoch : 4, loss: -6.7290
epoch : 5, loss: -7.0204
epoch : 6, loss: -7.1804
epoch : 7, loss: -7.2166
epoch : 8, loss: -7.2744
epoch : 9, loss: -7.3681
epoch : 10, loss: -7.4384
epoch : 11, loss: -7.6173
epoch : 12, loss: -7.6814
epoch : 13, loss: -7.8666
epoch : 14, loss: -7.8490
epoch : 15, loss: -7.8160
epoch : 16, loss: -8.0342
epoch : 17, loss: -8.0849
epoch : 18, loss: -8.1395
epoch : 19, loss: -8.3580
epoch : 20, loss: -8.3230
epoch : 21, loss: -8.2408
epoch : 22, loss: -8.4622
epoch : 23, loss: -8.4314
epoch : 24, loss: -8.3515
epoch : 25, loss: -8.6149
epoch : 26, loss: -8.6788
epoch : 27, loss: -8.7749
epoch : 28, loss: -8.6957
epoch : 29, loss: -8.7397
epoch : 30, loss: -8.9656
epoch : 31, loss: -8.7758
epoch : 32, loss: -8.9339
epoch : 33, loss: -8.9795
epoch : 34, loss: -8.8873
epoch : 35, loss: -8.8877
epoch : 36, loss: -9.1164
epoch : 37, loss: -9.0256
epoch : 38, loss: -9.1221
epoch : 39, loss: -9.

In [6]:
dtest = model(X_test)
mape(dtest, Y_test)

(tensor(0.0480, grad_fn=<MeanBackward0>),
 tensor([0.0396, 0.0462, 0.0483, 0.0592, 0.0545, 0.0401],
        grad_fn=<MeanBackward1>),
 tensor([0.0280, 0.0343, 0.0410, 0.0450, 0.0447, 0.0370],
        grad_fn=<StdBackward1>))

In [7]:
rmse(dtest, Y_test)

(tensor(0.0618, grad_fn=<PowBackward0>),
 tensor([0.0031, 0.0035, 0.0037, 0.0052, 0.0045, 0.0030],
        grad_fn=<MeanBackward1>),
 tensor([0.0052, 0.0053, 0.0065, 0.0088, 0.0080, 0.0062],
        grad_fn=<StdBackward1>))

In [8]:
nll(dtest, Y_test)

(tensor(-8.1108, grad_fn=<MeanBackward0>),
 tensor([-8.7502e+00, -5.9732e+00, -6.7567e+00, -4.9074e+00, -7.7975e+00,
         -1.1761e+01, -1.0583e+01, -7.3612e+00, -1.3845e+01, -6.7400e+00,
         -1.1705e+01, -8.2219e+00, -6.1231e+00, -7.8033e+00, -9.0829e+00,
         -9.3153e+00, -1.2820e+01, -4.5348e+00, -9.5028e+00, -1.2531e+01,
         -1.0749e+01, -1.0727e+01, -1.1015e+01, -1.2848e+01, -1.3418e+01,
         -7.3542e+00, -1.0408e+01, -5.1937e+00, -6.3420e+00, -1.2606e+01,
         -8.8712e+00, -1.3379e+01, -8.4305e+00, -5.9590e+00, -1.3701e+01,
         -9.0882e+00,  2.9273e+00,  2.2659e+00, -7.2122e+00, -1.0374e+01,
          1.3774e+01, -1.1525e+01, -1.0421e+01, -1.0747e+01, -1.0013e+01,
         -1.1060e+01, -6.4161e+00,  6.0504e+00, -1.0925e+01, -5.6095e+00,
         -4.8863e+00, -1.1789e+01, -9.6209e+00, -8.0307e+00, -1.0349e+00,
         -9.9630e+00, -6.3635e+00, -1.0424e+01,  8.7066e-01, -9.7633e+00,
         -1.0136e+01, -1.3015e+01, -1.0232e+01, -1.1967e+01, -6.0006e

### Full Covariance Matrix

In [16]:
hidden_layers = [20, 20, 20]
model = GaussianNeuralNet(1, 24, hidden_layers, 1, 6, full_covariance=True)

In [17]:
train(model, X_batches, Y_batches, num_epochs=40)

epoch : 1, loss: 1.9579
epoch : 2, loss: -0.4639
epoch : 3, loss: -2.9456
epoch : 4, loss: -3.6897
epoch : 5, loss: -4.0701
epoch : 6, loss: -4.2036
epoch : 7, loss: -4.2067
epoch : 8, loss: -5.1819
epoch : 9, loss: -5.6096
epoch : 10, loss: -4.8058
epoch : 11, loss: -6.1681
epoch : 12, loss: -6.2373
epoch : 13, loss: -6.5909
epoch : 14, loss: -6.7039
epoch : 15, loss: -6.8232
epoch : 16, loss: -6.9292
epoch : 17, loss: -7.2709
epoch : 18, loss: -7.4261
epoch : 19, loss: -7.3875
epoch : 20, loss: -7.2843
epoch : 21, loss: -7.7266
epoch : 22, loss: -7.7440
epoch : 23, loss: -7.9582
epoch : 24, loss: -7.8083
epoch : 25, loss: -8.0645
epoch : 26, loss: -7.8274
epoch : 27, loss: -8.0487
epoch : 28, loss: -8.3766
epoch : 29, loss: -7.5410
epoch : 30, loss: -8.5056
epoch : 31, loss: -8.5110
epoch : 32, loss: -7.6709
epoch : 33, loss: -8.3416
epoch : 34, loss: -8.7486
epoch : 35, loss: -8.8426
epoch : 36, loss: -8.9956
epoch : 37, loss: -8.4778
epoch : 38, loss: -9.0986
epoch : 39, loss: -9.4

In [18]:
dtest = model(X_test)
mape(dtest, Y_test)

(tensor(0.0876, grad_fn=<MeanBackward0>),
 tensor([0.0624, 0.0814, 0.0863, 0.1056, 0.1009, 0.0891],
        grad_fn=<MeanBackward1>),
 tensor([0.0586, 0.0809, 0.0932, 0.0958, 0.1026, 0.0955],
        grad_fn=<StdBackward1>))

In [19]:
rmse(dtest, Y_test)

(tensor(0.1114, grad_fn=<PowBackward0>),
 tensor([0.0062, 0.0112, 0.0126, 0.0182, 0.0152, 0.0110],
        grad_fn=<MeanBackward1>),
 tensor([0.0097, 0.0182, 0.0223, 0.0286, 0.0240, 0.0175],
        grad_fn=<StdBackward1>))

In [20]:
nll(dtest, Y_test)

(tensor(-9.4055, grad_fn=<MeanBackward0>),
 tensor([ -4.9001, -12.9676, -10.8576, -10.5229,  -8.4864, -10.8660,  -8.8562,
         -11.2543, -13.8468, -10.1516,  -9.8731, -13.3549, -12.4451,  -8.2413,
         -12.3121,  -8.1515, -11.7050,  -5.4832,  -6.3863,  -8.4444,  -9.0671,
          -8.7400,  -7.5044,  -9.2459, -12.1668,  -5.5487,  -5.6535,  -5.5250,
         -10.0090, -12.3646, -10.9982, -13.5582,  -5.3327,  -8.9726,  -6.7702,
         -11.4305,  -7.5703,  -1.8184,  -9.6096, -12.7866,  -3.6769,  -7.0084,
         -11.6900, -11.7762,  -9.5284, -13.4463,  -6.3791,  -8.7735, -12.4269,
         -12.6772,  -8.3314, -10.7578,  -7.0895,  -7.6063,  -7.6337, -10.4535,
          -5.6126,  -5.5827, -10.9178,  -8.4472, -11.1533,  -9.7813,  -8.6840,
         -10.3994, -10.9895,  -7.9864,  -8.7435, -12.6852, -10.9181, -12.4962,
          -7.7773,  -8.9575, -13.6984, -12.1688,  -8.3597, -10.1549,  -5.6237,
         -12.8625,  -1.9078, -11.6788,  -7.4020,  -7.7809, -11.8759,  -9.4665,
         